# -*- mode: ruby -*-
# vi: set ft=ruby :
 
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
 
Vagrant.configure(2) do |config|
    config.vm.synced_folder ".", "/vagrant", type:"virtualbox"
    if Vagrant.has_plugin?("vagrant-timezone")
        config.timezone.value = "Asia/Bangkok"
    end
    config.vm.define "node1" do |node|
        node.vm.box = "bento/centos-7.3"
        node.vm.hostname = "mysql-node1"
        node.vm.network :private_network, ip: "10.1.0.11"
    end
     
    config.vm.define "node2" do |node|
        node.vm.box = "bento/centos-7.3"
        node.vm.hostname = "mysql-node2"
        node.vm.network :private_network, ip: "10.1.0.12"
    end
     
    config.vm.define "node3" do |node|
        node.vm.box = "bento/centos-7.3"
        node.vm.hostname = "mysql-node3"
        node.vm.network :private_network, ip: "10.1.0.13"
    end
     
    config.vm.define "web" do |node|
        node.vm.box = "bento/centos-7.3"
        node.vm.hostname = "mysql-web"
        node.vm.network :private_network, ip: "10.1.0.10"
    end
end
